using Microsoft.AspNetCore.Components;
using MudBlazor;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FitUP.Pages;

public partial class DicasTreino
{
    // ========== TÉCNICAS AVANÇADAS ==========

    private async Task AbrirDetalhesTecnica(TecnicaAvancadaModel tecnica)
    {
        var options = new DialogOptions { CloseOnEscapeKey = true, MaxWidth = MaxWidth.Small, FullWidth = true };
        var parameters = new DialogParameters<MensagemCustomizada> { { x => x.Titulo, tecnica.Nome }, { x => x.Conteudo, tecnica.Explicacao } };
        await DialogService.ShowAsync<MensagemCustomizada>("Detalhes da Técnica", parameters, options);
    }

    private async Task AbrirExemploTecnica(TecnicaAvancadaModel tecnica)
    {
        var options = new DialogOptions { CloseOnEscapeKey = true, MaxWidth = MaxWidth.Small, FullWidth = true };
        var sb = new System.Text.StringBuilder();
        sb.Append("<div class='mud-table mud-simple-table mud-table-bordered mud-table-striped mud-elevation-1 mt-2'><div class='mud-table-container'><table class='mud-table-root'><thead class='mud-table-head' style='background-color: rgba(255,107,53,0.1);'><tr class='mud-table-row'><th class='mud-table-cell' style='color:coral; font-weight:bold;'>Passo</th><th class='mud-table-cell' style='color:coral; font-weight:bold;'>Ação</th><th class='mud-table-cell' style='color:coral; font-weight:bold;'>Detalhe</th></tr></thead><tbody class='mud-table-body'>");
        foreach (var p in tecnica.PassosPraticos)
            sb.Append($"<tr class='mud-table-row'><td class='mud-table-cell'><b>{p.Passo}</b></td><td class='mud-table-cell'>{p.Acao}</td><td class='mud-table-cell'>{p.Detalhe}</td></tr>");
        sb.Append("</tbody></table></div></div>");
        var p2 = new DialogParameters<MensagemCustomizada> { { x => x.Titulo, $"Como Aplicar: {tecnica.Nome}" }, { x => x.Conteudo, sb.ToString() } };
        await DialogService.ShowAsync<MensagemCustomizada>("Exemplo Prático", p2, options);
    }

    public class TecnicaAvancadaModel
    {
        public string Nome { get; set; } = "";
        public string Tagline { get; set; } = "";
        public string Descricao { get; set; } = "";
        public string Nivel { get; set; } = "";
        public string QuandoUsar { get; set; } = "";
        public string Icone { get; set; } = "";
        public bool Inverter { get; set; }
        public string CardGradient { get; set; } = "";
        public List<string> Beneficios { get; set; } = new();
        public string Explicacao { get; set; } = "";
        public List<PassoPratico> PassosPraticos { get; set; } = new();
    }

    public class PassoPratico
    {
        public string Passo { get; set; } = "";
        public string Acao { get; set; } = "";
        public string Detalhe { get; set; } = "";
    }

    private List<TecnicaAvancadaModel> ListaTecnicas = new()
    {
        new TecnicaAvancadaModel { Nome = "Drop Set", Tagline = "Alongue sua série até a falha total", Descricao = "Após atingir a falha com sua carga de trabalho, reduza o peso em 20-30% e continue sem descanso até nova falha. Pode-se fazer uma, duas ou três reduções consecutivas (double/triple drop). Ideal para o final do treino.", Nivel = "Intermediário a Avançado", QuandoUsar = "Final do treino, último exercício", Icone = Icons.Material.Filled.TrendingDown, Inverter = false, CardGradient = "linear-gradient(135deg, #2d1b4e 0%, #1a0d30 100%)", Beneficios = new() { "Leva o músculo à falha absoluta", "Recruta fibras profundas", "Excelente para quebrar platôs", "Aumenta pump e densidade" }, Explicacao = "O Drop Set foi popularizado por Arnold Schwarzenegger e consiste em estender uma série além da falha reduzindo a carga progressivamente. Estudos mostram que essa técnica gera um estresse metabólico extremo, um dos três principais mecanismos de hipertrofia. As fibras de contração rápida (Tipo II) são forçadas a trabalhar mesmo com cargas reduzidas, pois as fibras lentas já estão completamente exauridas. Aplique 1-2 drop sets por grupamento em máquinas, polias ou halteres; evite exercícios com barra livre onde a falha pode comprometer a segurança.", PassosPraticos = new() { new() { Passo = "1", Acao = "Série Base", Detalhe = "Faça 8-12 reps até a falha com sua carga normal" }, new() { Passo = "2", Acao = "1ª Queda", Detalhe = "Reduza 20-30% do peso e continue sem descanso até nova falha" }, new() { Passo = "3", Acao = "2ª Queda", Detalhe = "Reduza mais 20-30% e vá até a falha absoluta (opcional)" }, new() { Passo = "4", Acao = "Descanso", Detalhe = "Descanse 2-3 min antes de repetir (máx. 1-2 drop sets)" } } },
        new TecnicaAvancadaModel { Nome = "Rest-Pause", Tagline = "Pequenas pausas, grandes ganhos de força", Descricao = "Execute o máximo de repetições com carga pesada (85-90% de 1RM), descanse apenas 15-20 segundos, e então repita até a falha novamente. Repita esse ciclo 2-3 vezes, acumulando muito mais volume com cargas elevadas do que séries tradicionais.", Nivel = "Intermediário a Avançado", QuandoUsar = "Exercícios compostos pesados (supino, agachamento)", Icone = Icons.Material.Filled.PauseCircle, Inverter = true, CardGradient = "linear-gradient(135deg, #1a3a5c 0%, #0d1f33 100%)", Beneficios = new() { "Aumenta volume com cargas elevadas", "Recruta unidades motoras de alto limiar", "Excelente para ganhos de força", "Permite progressão constante" }, Explicacao = "O Rest-Pause foi desenvolvido por Mike Mentzer no Heavy Duty Training. A premissa é simples: cargas pesadas (85-90% de 1RM) recrutam todas as unidades motoras, mas o número de repetições é limitado pela fadiga. Pausas curtas (15-20s) permitem ressíntese parcial de ATP, viabilizando mais repetições com a mesma carga. O resultado é estímulo de força e hipertrofia miofibrilar superior. Aplique nos primeiros exercícios do treino, com sistema nervoso fresco, e priorize exercícios onde a segurança não é comprometida pela fadiga extrema.", PassosPraticos = new() { new() { Passo = "1", Acao = "Série Inicial", Detalhe = "Use 85-90% da carga máxima e faça o máximo de reps (4-6)" }, new() { Passo = "2", Acao = "Pausa Curta", Detalhe = "Descanse exatamente 15-20 segundos (use cronômetro)" }, new() { Passo = "3", Acao = "Repetir", Detalhe = "Faça mais 2-3 reps e repita o ciclo mais 1-2 vezes" }, new() { Passo = "4", Acao = "Finalizar", Detalhe = "Após 2-3 ciclos, descanse 3-4 min antes da próxima série" } } },
        new TecnicaAvancadaModel { Nome = "Bi-Set", Tagline = "Dois exercícios consecutivos, zero descanso", Descricao = "Execute dois exercícios diferentes para o mesmo grupamento muscular, um seguido do outro sem intervalo. Ex: Supino Reto seguido de Crucifixo (ambos para peito). Só descanse após completar ambos. Isso atinge diferentes ângulos e porções do músculo em uma única série estendida.", Nivel = "Iniciante a Avançado", QuandoUsar = "Qualquer fase do treino, dias de volume", Icone = Icons.Material.Filled.SyncAlt, Inverter = false, CardGradient = "linear-gradient(135deg, #1e3b2e 0%, #0f1f18 100%)", Beneficios = new() { "Economiza tempo de treino", "Aumenta densidade de treino", "Ataca o músculo de ângulos diferentes", "Excelente pump e vascularização" }, Explicacao = "O Bi-Set é frequentemente confundido com o Super-Set, mas há uma diferença fundamental: no Bi-Set, ambos os exercícios são para o MESMO grupamento (ex: Supino + Crucifixo). Já no Super-Set, são grupamentos ANTAGONISTAS (ex: Bíceps + Tríceps). O Bi-Set gera acúmulo metabólico extremo porque o músculo não descansa entre os dois estímulos. A chave é escolher exercícios complementares: um composto seguido de um isolador, ou dois com ângulos diferentes. Evite Bi-Set em exercícios de alta complexidade como terra ou agachamento pesado.", PassosPraticos = new() { new() { Passo = "1", Acao = "1º Exercício", Detalhe = "Execute o composto (ex: Supino Reto) até a falha ou próximo dela" }, new() { Passo = "2", Acao = "Sem Descanso", Detalhe = "Imediatamente vá para o 2º exercício isolador (ex: Crucifixo)" }, new() { Passo = "3", Acao = "2º Exercício", Detalhe = "Execute até a falha, focando na contração máxima" }, new() { Passo = "4", Acao = "Descanso", Detalhe = "Descanse 90-120 segundos e repita por 2-3 rodadas" } } },
        new TecnicaAvancadaModel { Nome = "Pirâmide", Tagline = "Suba e desça as cargas com precisão", Descricao = "Comece com cargas leves e altas repetições, aumentando o peso e reduzindo as reps a cada série (crescente). Ou faça o inverso (decrescente). A versão completa sobe e depois desce, combinando estímulos de resistência, hipertrofia e força no mesmo exercício. Ideal para o primeiro exercício do dia.", Nivel = "Iniciante a Avançado", QuandoUsar = "Primeiro exercício do treino (exercício principal)", Icone = Icons.Material.Filled.ShowChart, Inverter = true, CardGradient = "linear-gradient(135deg, #4a3510 0%, #2e1f08 100%)", Beneficios = new() { "Aquece progressivamente articulações", "Trabalha diferentes faixas de repetições", "Permite alta carga com segurança", "Ideal para exercícios compostos pesados" }, Explicacao = "A Pirâmide é uma das técnicas mais antigas e eficazes. A Pirâmide Crescente serve como aquecimento progressivo — você começa com 15 reps leves, depois 12, 10, 8 e 6 reps aumentando a carga. Isso prepara o sistema nervoso e as articulações para a carga máxima no topo. Já a Pirâmide Completa adiciona a descida: após o pico (ex: 6 reps com 100kg), reduza o peso e suba as repetições (8, 10, 12, 15). Isso cria um estímulo híbrido poderoso: séries pesadas recrutam fibras de alta potência, e as leves finais geram estresse metabólico quando o músculo já está fatigado.", PassosPraticos = new() { new() { Passo = "1", Acao = "Aquecimento", Detalhe = "1-2 séries leves (50-60% da carga) para lubrificar as articulações" }, new() { Passo = "2", Acao = "Subida", Detalhe = "Aumente a carga a cada série, reduzindo reps (15→12→10→8→6)" }, new() { Passo = "3", Acao = "Pico", Detalhe = "Série mais pesada no topo (4-6 reps com 85-90% da carga máxima)" }, new() { Passo = "4", Acao = "Descida", Detalhe = "Reduza carga e suba reps de volta (8→10→12→15) para pump final" } } },
        new TecnicaAvancadaModel { Nome = "Super Slow", Tagline = "Cadência controlada para máxima tensão", Descricao = "Execute cada repetição com velocidade extremamente lenta e controlada: 5-10 segundos na fase excêntrica (descida) e 5-10 segundos na concêntrica (subida), sem nunca travar as articulações. Elimina completamente o impulso, forçando o músculo a trabalhar continuamente.", Nivel = "Intermediário a Avançado", QuandoUsar = "Deload, volta de lesão ou quebra de platô", Icone = Icons.Material.Filled.SlowMotionVideo, Inverter = false, CardGradient = "linear-gradient(135deg, #1a4050 0%, #0d2430 100%)", Beneficios = new() { "Elimina completamente o impulso", "Aumenta tempo sob tensão", "Reduz risco de lesão por carga", "Excelente para conexão mente-músculo" }, Explicacao = "O Super Slow, desenvolvido por Ken Hutchins, anula o momento (impulso) — o maior ladrão de hipertrofia. Com cadência 10/10 (10s descendo, 10s subindo), cada repetição dura 20 segundos, então uma série de apenas 4-6 repetições já gera 80-120 segundos de tempo sob tensão contínua. A carga precisa ser drasticamente reduzida (40-60% da normal). É excelente para fases de deload, recuperação de lesões, ou para ensinar iniciantes a sentir o músculo trabalhando (conexão mente-músculo).", PassosPraticos = new() { new() { Passo = "1", Acao = "Carga Reduzida", Detalhe = "Use apenas 40-60% da sua carga normal de trabalho" }, new() { Passo = "2", Acao = "Fase Excêntrica", Detalhe = "Desça o peso em 5-10 segundos, controlando cada centímetro" }, new() { Passo = "3", Acao = "Fase Concêntrica", Detalhe = "Suba o peso em 5-10 segundos, sem trancar a articulação no topo" }, new() { Passo = "4", Acao = "Sem Pausa", Detalhe = "Mantenha tensão constante por 4-6 reps, sem descanso no topo/base" } } },
        new TecnicaAvancadaModel { Nome = "Pré-Exaustão", Tagline = "Isole o músculo antes do exercício composto", Descricao = "Execute primeiro um exercício isolador para fatigar o músculo-alvo e, em seguida, um composto onde esse mesmo músculo é sinergista. Ex: Crucifixo (isolador) seguido de Supino Reto (composto). No supino, o peito já fatigado falhará antes dos tríceps e ombros, garantindo que o alvo seja o limitante.", Nivel = "Avançado", QuandoUsar = "Fases de especialização em ponto fraco", Icone = Icons.Material.Filled.Whatshot, Inverter = true, CardGradient = "linear-gradient(135deg, #5c1a1a 0%, #330d0d 100%)", Beneficios = new() { "Força o músculo-alvo a ser o limitante", "Útil para vencer desequilíbrios", "Alta ativação de fibras profundas", "Excelente para ponto fraco" }, Explicacao = "A Pré-Exaustão resolve um problema clássico: em exercícios compostos, o músculo menor (sinergista) costuma falhar antes do alvo. Exemplo: no supino, o tríceps frequentemente falha antes do peito. Ao fazer crucifixo primeiro, o peito chega ao supino já fatigado, enquanto o tríceps está fresco. Assim, quando você falhar no supino, a falha terá sido do peito — não do tríceps. Técnica avançada para quem já tem boa consciência corporal e deseja especializar um grupamento específico.", PassosPraticos = new() { new() { Passo = "1", Acao = "Isolador", Detalhe = "Faça 8-12 reps de um isolador (ex: Crucifixo) até a falha" }, new() { Passo = "2", Acao = "Sem Descanso", Detalhe = "Imediatamente vá para o composto (ex: Supino Reto)" }, new() { Passo = "3", Acao = "Composto", Detalhe = "Execute o composto até a falha — o alvo já estará fatigado" }, new() { Passo = "4", Acao = "Descanso", Detalhe = "Descanse 2-3 min e repita no máximo 1-2 vezes por grupamento" } } },
        new TecnicaAvancadaModel { Nome = "Cluster Set", Tagline = "Explosão controlada com pausas intra-série", Descricao = "Divida uma série pesada em mini-blocos com pausas curtas. Ex: em vez de 6 reps contínuas com 90% de 1RM, faça 2 reps, descanse 20s, +2 reps, +20s, +2 reps. Isso mantém a potência e velocidade de execução altas em todas as repetições, ao contrário de uma série tradicional onde as últimas ficam lentas.", Nivel = "Avançado", QuandoUsar = "Treinos de força e potência (powerbuilding)", Icone = Icons.Material.Filled.Bolt, Inverter = false, CardGradient = "linear-gradient(135deg, #3a3a3a 0%, #1c1c1c 100%)", Beneficios = new() { "Mantém potência em todas as reps", "Permite mais volume com carga alta", "Reduz desgaste do SNC", "Ideal para powerbuilding" }, Explicacao = "No Cluster Set, a qualidade de cada repetição é preservada. Em séries tradicionais pesadas, as primeiras reps são explosivas, mas as últimas ficam arrastadas — recrutando menos fibras de alto limiar. Ao inserir pausas de 15-30s a cada 1-3 reps, você permite ressíntese parcial de ATP sem perder a ativação neural. O resultado: todas as repetições são executadas com velocidade e potência máximas, crítico para ganhos de força e para atletas que precisam de potência sem acúmulo excessivo de fadiga.", PassosPraticos = new() { new() { Passo = "1", Acao = "Carga Elevada", Detalhe = "Escolha 85-92% da sua carga máxima (1RM)" }, new() { Passo = "2", Acao = "Mini-Bloco", Detalhe = "Faça 1-3 reps explosivas e pause 15-30s" }, new() { Passo = "3", Acao = "Repetir Blocos", Detalhe = "Repita por 3-5 blocos até acumular 6-9 reps totais com a carga" }, new() { Passo = "4", Acao = "Descanso Longo", Detalhe = "Descanse 3-5 min entre séries para recuperação neural total" } } },
        new TecnicaAvancadaModel { Nome = "Oclusão (Kaatsu)", Tagline = "Baixa carga, altíssima resposta hipertrófica", Descricao = "Utilize faixas elásticas para restringir parcialmente o fluxo sanguíneo no membro durante o exercício. Com apenas 20-30% da carga máxima e altas repetições (15-30), a restrição de oxigênio gera um ambiente metabólico extremo que estimula hipertrofia significativa com mínimo estresse articular.", Nivel = "Avançado (requer supervisão)", QuandoUsar = "Fases de recuperação ou final de treino", Icone = Icons.Material.Filled.Favorite, Inverter = true, CardGradient = "linear-gradient(135deg, #4a1a3a 0%, #2e0d22 100%)", Beneficios = new() { "Hipertrofia com cargas muito baixas", "Preserva articulações", "Recruta fibras Tipo II indiretamente", "Ótimo em fases de recuperação" }, Explicacao = "Oclusão Vascular ou Kaatsu Training foi desenvolvido no Japão pelo Dr. Yoshiaki Sato. A restrição parcial do fluxo venoso (não arterial) cria um acúmulo de metabólitos (lactato, íons de hidrogênio) que estimulam a liberação de hormônio do crescimento (GH) e ativam fibras de contração rápida mesmo com cargas leves. IMPORTANTE: Esta técnica requer conhecimento sobre pressão de oclusão e posicionamento correto. Uso incorreto pode causar danos vasculares. Busque orientação profissional antes de aplicar.", PassosPraticos = new() { new() { Passo = "1", Acao = "Posicionamento", Detalhe = "Coloque a faixa na porção superior do braço/coxa (pressão 5-7/10)" }, new() { Passo = "2", Acao = "Carga Baixa", Detalhe = "Use apenas 20-30% de 1RM — a carga não é o fator principal" }, new() { Passo = "3", Acao = "Altas Reps", Detalhe = "Execute 15-30 reps (ou 4 séries de 15 com 30s de descanso)" }, new() { Passo = "4", Acao = "Remoção Imediata", Detalhe = "Solte a faixa assim que terminar; mantenha por no máximo 10-15 min" } } }
    };
}